title: i5possible 

name: Hong Liang
description: 
    # I have "possible"! <br />
    # I got everything done!
markdown: kramdown

permalink: /:categories/:title.html
show_excerpts: true
excerpt_separator: <!--more-->

defaults: 
    -
        scope:
            path: ""
        values:
            layout: "default"
            author: "Hong Liang"
    -
        scope:
            path: "post"
            type: "tips"
        values:
            layout: "default"
    -
        scope:
            path: "thoughts"
            type: "thoughts"
        values:
            layout: "default"
    -
        scope:
            path: "dairy"
            type: "dairy"
        values:
            layout: "default"

# theme: jekyll-theme-cayman
theme: jekyll-theme-hacker
