title: i5possible 

name: Hong Liang, Thoughtworks
description: I have "possible", I got everything done!
markdown: kramdown


defaults: 
    -
        scope:
            path: "post"
            type: "posts"
        values:
            layout: "default"

theme: jekyll-theme-cayman

